# Generated by Django 2.0 on 2017-12-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='created_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='memory',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
