# Generated by Django 2.0 on 2018-01-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='city',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='country',
        ),
    ]
