# Generated by Django 2.0 on 2017-12-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='title',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='date2',
        ),
        migrations.AddField(
            model_name='memory',
            name='country',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
